package clickhouse

var ClickHouseKeywords = map[string]bool{
	"ADD": true, "AFTER": true, "ALIAS": true, "ALL": true, "ALTER": true,
	"AND": true, "ANTI": true, "ANY": true, "ARRAY": true, "AS": true,
	"ASCENDING": true, "ASOF": true, "AST": true, "ASYNC": true, "ATTACH": true,
	"BETWEEN": true, "BOTH": true, "BY": true, "CASE": true, "CAST": true,
	"CHECK": true, "CLEAR": true, "CLUSTER": true, "CODEC": true, "COLLATE": true,
	"COLUMN": true, "COMMENT": true, "CONSTRAINT": true, "CREATE": true, "CROSS": true,
	"CUBE": true, "CURRENT": true, "DATABASE": true, "DATABASES": true, "DATE": true,
	"DAY": true, "DEDUPLICATE": true, "DEFAULT": true, "DELAY": true, "DELETE": true,
	"DESC": true, "DESCENDING": true, "DESCRIBE": true, "DETACH": true, "DICTIONARIES": true,
	"DICTIONARY": true, "DISK": true, "DISTINCT": true, "DISTRIBUTED": true, "DROP": true,
	"ELSE": true, "END": true, "ENGINE": true, "EVENTS": true, "EXISTS": true,
	"EXPLAIN": true, "EXPRESSION": true, "EXTRACT": true, "FETCHES": true, "FILL": true,
	"FINAL": true, "FIRST": true, "FLUSH": true, "FOLLOWING": true, "FOR": true,
	"FORMAT": true, "FREEZE": true, "FROM": true, "FULL": true, "FUNCTION": true,
	"GLOBAL": true, "GRANULARITY": true, "GROUP": true, "HAVING": true, "HIERARCHICAL": true,
	"HOUR": true, "ID": true, "IF": true, "ILIKE": true, "IN": true,
	"INDEX": true, "INF": true, "INJECTIVE": true, "INNER": true, "INSERT": true,
	"INTERVAL": true, "INTO": true, "IS": true, "IS_OBJECT_ID": true, "JOIN": true,
	"KEY": true, "KILL": true, "LAST": true, "LAYOUT": true, "LEADING": true,
	"LEFT": true, "LIFETIME": true, "LIKE": true, "LIMIT": true, "LIVE": true,
	"LOCAL": true, "LOGS": true, "MATERIALIZE": true, "MATERIALIZED": true, "MAX": true,
	"MERGES": true, "MIN": true, "MINUTE": true, "MODIFY": true, "MONTH": true,
	"MOVE": true, "MUTATION": true, "NAN": true, "NO": true, "NOT": true,
	"NULL": true, "NULLS": true, "OFFSET": true, "ON": true, "OPTIMIZE": true,
	"OR": true, "ORDER": true, "OUTER": true, "OUTFILE": true, "OVER": true,
	"PARTITION": true, "POPULATE": true, "PRECEDING": true, "PREWHERE": true, "PRIMARY": true,
	"PROJECTION": true, "QUARTER": true, "RANGE": true, "RELOAD": true, "REMOVE": true,
	"RENAME": true, "REPLACE": true, "REPLICA": true, "REPLICATED": true, "RIGHT": true,
	"ROLLUP": true, "ROW": true, "ROWS": true, "SAMPLE": true, "SECOND": true,
	"SELECT": true, "SEMI": true, "SENDS": true, "SET": true, "SETS": true,
	"SETTING": true, "SETTINGS": true, "SHOW": true, "SOURCE": true, "START": true,
	"STOP": true, "SUBSTRING": true, "SYNC": true, "SYNTAX": true, "SYSTEM": true,
	"TABLE": true, "TABLES": true, "TEMPORARY": true, "TEST": true, "THEN": true,
	"TIES": true, "TIME": true, "TIMEOUT": true, "TIMESTAMP": true, "TO": true,
	"TOP": true, "TOTALS": true, "TRAILING": true, "TRIM": true, "TRUNCATE": true,
	"TTL": true, "TUPLE": true, "TYPE": true, "UNBOUNDED": true, "UNION": true,
	"UPDATE": true, "USE": true, "USER": true, "USING": true, "UUID": true,
	"VALUES": true, "VIEW": true, "VOLUME": true, "WATCH": true, "WEEK": true,
	"WHEN": true, "WHERE": true, "WINDOW": true, "WITH": true, "YEAR": true,
}
